export const colors = {
  ink: '#16364d',
  muted: '#496d86',
  accent: '#ff8d4d',
  accentStrong: '#ff6b3d',
  accentSoft: '#ffe1c9',
  sky: '#bfe0f2',
  skyDeep: '#8ec8ea',
  paper: '#f6fbff',
  line: '#dfeaf1',
  soft: '#edf8ff',
  white: '#ffffff',
  error: '#b94b39',
  glass: '#f3fbffef',
  success: '#64b98d',
  gold: '#fbcf6f',
} as const;
